M48
; DRILL file {KiCad (6.0.7)} date Tue 20 Sep 2022 02:36:08 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-20T14:36:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X3.8921Y-1.5281
X4.1197Y-1.5281
T2
X3.4843Y-1.4278
T0
M30
